name: Flutter Build

on: [push]

jobs:
  build:
    runs-on: windows-latest #windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: repeatio/flutter-tetris
      # apk 才要装 java吧？
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - run: flutter config --enable-windows-desktop
      - run: flutter channel master
      - run: flutter upgrade
      - run: flutter pub get
      # skip test
      - run: flutter build windows

      #flutter build apk 输出
      #Built build/app/outputs/apk/release/app-release.apk (17.4MB).

      - if: success()
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
